// ==UserScript==
// @name         Better xCloud Web Lab - Pestaña Laboratorio
// @namespace    https://github.com/pigletgamer0-art/better-xcloud-desktop.
// @version      0.1.1
// @description  Una pestaña especial dentro del menú de ajustes, sin overlays sobre el juego.
// @match        https://www.xbox.com/play*
// @match        https://www.xbox.com/*/play*
// @grant        none
// @run-at       document-idle
// ==/UserScript==
(()=>{'use strict';
const KEY='bx-web-lab-url',DEFAULT='https://pigletgamer0-art.github.io/better-xcloud-desktop./web/',SVG='http://www.w3.org/2000/svg';
const H=(tag,text,attrs={})=>{const e=document.createElement(tag);if(text!==null)e.textContent=text;for(const [k,v] of Object.entries(attrs))e.setAttribute(k,v);return e;};
const getUrl=()=>{try{return localStorage.getItem(KEY)||DEFAULT;}catch{return DEFAULT;}};
function openUrl(s){try{const u=new URL(s);if(!['http:','https:'].includes(u.protocol))throw Error('protocol');window.open(u.href,'_blank','noopener,noreferrer');}catch{alert('La dirección debe empezar con https:// o http://');}}
function makeTab(){const svg=document.createElementNS(SVG,'svg');for(const [k,v] of Object.entries({viewBox:'0 0 24 24',width:'32',height:'32',fill:'none',stroke:'currentColor','stroke-width':'1.7','stroke-linecap':'round',role:'tab','aria-label':'Laboratorio web',title:'Laboratorio web',tabindex:'0'}))svg.setAttribute(k,v);svg.dataset.group='laboratorio';svg.classList.add('bx-lab-tab');const path=document.createElementNS(SVG,'path');path.setAttribute('d','M8 3h8M9 3v6l-5 8a3 3 0 0 0 2.6 4.5h10.8A3 3 0 0 0 20 17L15 9V3M7 16h10M9 12h6');svg.append(path);return svg;}
function makeContent(){const c=H('section',null,{'data-tab-group':'laboratorio',class:'bx-gone bx-lab-content'}),input=H('input',null,{type:'url',id:'bx-lab-url',autocomplete:'url'});input.value=getUrl();const status=H('p','',{role:'status'}),open=H('button','Abrir Better xCloud Web Lab ↗',{type:'button'}),save=H('button','Guardar dirección',{type:'button'});open.addEventListener('click',()=>openUrl(input.value));save.addEventListener('click',()=>{try{const u=new URL(input.value);if(!['http:','https:'].includes(u.protocol))throw Error('protocol');localStorage.setItem(KEY,u.href);status.textContent='Dirección guardada.';}catch{status.textContent='Introduce una URL http(s) válida.';}});c.append(H('h2','Laboratorio web'),H('p','Tus herramientas de configuración están aquí, en una pestaña. No se añaden barras flotantes a la transmisión.'),open,H('label','Dirección de tu versión web:',{for:'bx-lab-url'}),input,save,status,H('p','El streaming de Xbox requiere Internet. La interfaz de Web Lab puede abrirse offline después de instalar la PWA, pero no incluye juegos locales.'));return c;}
function attach(){const root=document.querySelector('.bx-settings-dialog');if(!root)return;const tabs=root.querySelector('.bx-settings-tabs'),panels=root.querySelector('.bx-settings-tab-content');if(!tabs||!panels||tabs.querySelector('[data-group="laboratorio"]')||!tabs.querySelector('svg[data-group]'))return;
if(!document.getElementById('bx-lab-style'))document.head.append(H('style',`.bx-lab-tab{cursor:pointer;padding:5px;border-radius:8px;color:inherit}.bx-lab-tab.bx-active,.bx-lab-tab:hover{background:#42792a}.bx-lab-content{padding:17px;overflow:auto;max-width:650px;color:white}.bx-lab-content.bx-gone{display:none!important}.bx-lab-content h2{font-size:1.2rem}.bx-lab-content p{font-size:.9rem;line-height:1.6;opacity:.85}.bx-lab-content label{display:block;font-size:.85rem;margin:14px 0 8px}.bx-lab-content input{width:100%;box-sizing:border-box;background:#111b16;border:1px solid #628251;color:white;border-radius:7px;padding:10px;font:inherit}.bx-lab-content button{cursor:pointer;background:#347629;color:white;border:1px solid #79bd52;border-radius:8px;padding:11px 14px;margin:10px 10px 10px 0;font-weight:bold`,{id:'bx-lab-style'}));
const tab=makeTab(),content=makeContent();tabs.append(tab);panels.append(content);const select=()=>{Array.from(panels.children).forEach(e=>{if(e.dataset.tabGroup)e.classList.toggle('bx-gone',e!==content);});Array.from(tabs.children).forEach(e=>e.classList.toggle('bx-active',e===tab));const sel=root.querySelector('.bx-settings-tab-contents > :first-child');if(sel&&sel!==panels)sel.classList.add('bx-gone');tab.focus();};tab.addEventListener('click',select);tab.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select();}});}
let scheduled=false;new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;attach();});}).observe(document.documentElement,{subtree:true,childList:true});attach();
})();